# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/asus/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter rog3 I002D,$(TARGET_DEVICE)),)

endif
